dist: trusty
sudo: required
language: csharp
mono: none
before_install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  - sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.1.3 -y --allow-unauthenticated
script:
  - dotnet restore
  - dotnet build
